package ru.opgmap.reports.models.enums;

import lombok.Getter;

@Getter
public enum ReportType {
    UNKNOWN,
    CONTENT_OF_A_SEXUAL_NATURE,
    VIOLENT_OR_REPULSIVE_SCENES,
    HARMFUL_OR_DANGEROUS_ACTIVITIES,
    CHILD_ABUSE,
    PROPAGANDA_OF_TERRORISM,
    SPAM_OR_FALSE_INFORMATION,
    VIOLATION_OF_MY_RIGHTS,
    PROBLEM_WITH_SUBTITLES,
    UNWANTED_ADVERTISING_OR_SPAM,
    PORNOGRAPHY_OR_EXPLICIT_SEX_SCENES,
    DISCRIMINATORY_LANGUAGE_OR_NATURALISTIC_CONTENT,
    INSULTS_OR_THREATS,
    CALL_TO_VIOLENCE,
    DISCLOSURE_OF_PERSONAL_INFORMATION,
    COPYRIGHT_INFRINGEMENT,
    OFFENSIVE_CONTENT_FOR_CHILDREN,
    INAPPROPRIATE_CONTENT,
    USES_A_DIFFERENT_NAME,
    INAPPROPRIATE_PROFILE_INFORMATION,
    THE_USER_IS_UNDER_THE_AGE_OF_THIRTEEN;

}
