server:
  port: 80

spring:
  application:
    name: REPORTS-SERVICE
  flyway:
    default-schema: public
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/opgmap_reports?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    request-timeout-ms: 1000
    reply-timeout-ms: 5000
    producer:
      batch-delay: 5000
      batch-size: 32000
    consumer:
      group-id: reports_consumer
    topic:
      addReport: add_report

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/realms/opgmap/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      clientSecret: fsTR31mMbOEOl9FSNw6oIZFGyVz8fYhY
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://localhost:8888/realms/opgmap/protocol/openid-connect/auth
    tokenUrl: http://localhost:8888/realms/opgmap/protocol/openid-connect/token

logging:
  level:
    org:
      springframework:
        security: DEBUG


eureka:
  instance:
    hostname: report-service
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
