server:
  forward-headers-strategy: framework

spring:
  application:
    name: REPORTS-SERVICE
  flyway:
    default-schema: public
  main:
    allow-bean-definition-overriding: true
  datasource:
    url:  ${POSTGRES_URL}/${POSTGRES_DB}?createDatabaseIfNotExist=true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    request-timeout-ms: 1000
    reply-timeout-ms: 5000
    producer:
      batch-delay: 5000
      batch-size: 32000
    consumer:
      group-id: reports_consumer
    topic:
      addReport: ${ADD_REPORT_TOPIC}
  zipkin:
    base-url: ${ZIPKIN_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_URL}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    oauth:
      clientId: ${SPRING_DOC_OAUTH2_CLIENT_ID}
      clientSecret: ${SPRING_DOC_OAUTH2_CLIENT_SECRET}
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: ${SPRINGDOC_KEYCLOAK_REALM_URL}/protocol/openid-connect/auth
    tokenUrl: ${SPRINGDOC_KEYCLOAK_REALM_URL}/protocol/openid-connect/token

logging:
  level:
    org:
      springframework:
        security: DEBUG


eureka:
  instance:
    hostname: ${EUREKA_CLIENT_HOST}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
    fetch-registry: true
